- name: Install mysql libraries
  ansible.builtin.pip: # ansible pip module
    name: "{{ item }}"
    executable: pip3.9 # To know present version of ansible- "ansible --version"
  loop:
  - cryptography
  - PyMySQL

- name: Install mysql server
  ansible.builtin.package: # ansible package module
    name: mysql-server
    state: present

- name: start and enable mysql
  ansible.builtin.service: # ansible start and enable service
    name: mysqld
    state: started
    enabled: yes

- name: connect to mysql server
  community.mysql.mysql_info: # ansible mysql module- mysql_info module
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: mysql.poojari.store
  register: mysql_info
  ignore_errors: true  # "ansible error handling" . In this we get error and we are telling that ignor it.

- name: print the output
  ansible.builtin.debug:
    msg: "mysql information: {{ mysql_info }}" 

- name: setup the login_password
  ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ mysql_root_password }}"
  when: mysql_info.failed is true    